### ISSUE TITLE
"Compositor doesn't support wlr-output-management-unstable-v1" despite said protocol being installed

### ISSUE THREAD

**Issue by SpaceBearOne** [luispabon/wdisplays#1]
When trying to run wdisplays, I am met with the message "Compositor doesn't support wlr-output-management-unstable-v1", even after having installed said protocols from the [wlr-protocols repository](https://github.com/swaywm/wlr-protocols/) repository, the only one where i could find it.

**Comment by luispabon** [comment]
Just a note, I don't really maintain this app - I forked it as development seemed to have stopped.

That said, wlr-protocols are just protocol definitions and won't give you what you're after. You probably need a newer version of sway, if that's the wm you're using atm.
